
services:

  cuborrubikcronometro:
    build: .
    restart: always
    env_file: ./.env
    ports:
      - 3008:3008
    environment:
      - URL_DB=$URL_DB_ENV
      - USERNAME=$USERNAME_ENV
      - PASSWORD=$PASSWORD_ENV
      - JWT_KEY=$JWT_KEY_ENV
      - PORT=3008
      - JWT_KEY_SOCKET=$JWT_KEY_SOCKET_ENV
      - JWT_KEY_REFRESH=$JWT_KEY_REFRESH_ENV